### ISSUE TITLE
Refactor lock API

### ISSUE THREAD

**Issue by benasher44** [touchlab/Stately#10]
The lock API could be refactored to require dispose/close (implement Closeable). If this were done, the native lock could move to pthread_lock for most native platforms (even os_unfair_lock on apple platforms). The current API design require lock cleanup.

**Comment by kpgalligan** [comment]
Done! The `close` method is currently an extension function so we can typealias implementations on some platforms. Trying to experiment and see if we can make "Stately" invisible on jvm. Also, for jvm and Apple platforms, you don't *need* to call close.
