### ISSUE TITLE
xcode cannot build release scheme

### ISSUE THREAD

**Issue by aplha98** [touchlab/Stately#104]
Could not find "co.touchlab:stately-common" in [/Users/ggg/Desktop/main/bas-ios_main/Pods, /Users/ggg/.konan/klib, /Users/ggg/.konan/kotlin-native-prebuilt-macos-x86_64-1.9.0/klib/common, /Users/ggg/.konan/kotlin-native-prebuilt-macos-x86_64-1.9.0/klib/platform/ios_arm64]

**Comment by kpgalligan** [comment]
You'll need to send your config. Kotlin version, libraries you're using and versions, etc.

**Comment by kpgalligan** [comment]
Haven't heard back. Closing for now.

**Comment by Lintom** [comment]
> You'll need to send your config. Kotlin version, libraries you're using and versions, etc.

Hi. I have this issue too.

Kotlin version - 1.9.20

Config

    kotlin {
	val sqldelight_version = "2.0.0"
	val koin_version = "3.5.0"
	val ktor_version = "2.3.4"
	val ktorfit_version = "1.10.1"

	commonMain.dependencies {
		implementation("app.cash.sqldelight:coroutines-extensions:$sqldelight_version")
		implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.5.0")
		implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1")
		implementation("co.touchlab:stately-concurrency:2.0.0")
		implementation("io.insert-koin:koin-core:$koin_version")
		implementation("io.insert-koin:koin-test:$koin_version")
		implementation("de.jensklingenberg.ktorfit:ktorfit-lib:$ktorfit_version")
		implementation("io.ktor:ktor-client-serialization:$ktor_version")
		implementation("io.ktor:ktor-client-content-negotiation:$ktor_version")
		implementation("io.ktor:ktor-serialization-kotlinx-json:$ktor_version")
		implementation("io.ktor:ktor-client-logging:$ktor_version")
		implementation("io.github.aakira:napier:2.6.1")
	}

	androidMain.dependencies {
		implementation("app.cash.sqldelight:android-driver:$sqldelight_version")
		implementation("io.insert-koin:koin-android:$koin_version")
		implementation("io.insert-koin:koin-androidx-workmanager:$koin_version")
		implementation("androidx.security:security-crypto:1.1.0-alpha06")
	}


	iosMain.dependencies {
		implementation("app.cash.sqldelight:native-driver:$sqldelight_version")
	}
    }

    dependencies {
    add("kspCommonMainMetadata", "de.jensklingenberg.ktorfit:ktorfit-ksp:$ktorfit_version")
    add("kspAndroid","de.jensklingenberg.ktorfit:ktorfit-ksp:$ktorfit_version")
    add("kspIosX64","de.jensklingenberg.ktorfit:ktorfit-ksp:$ktorfit_version")
    add("kspIosArm64","de.jensklingenberg.ktorfit:ktorfit-ksp:$ktorfit_version")
    add("kspIosSimulatorArm64","de.jensklingenberg.ktorfit:ktorfit-ksp:$ktorfit_version")
    }

**Comment by kpgalligan** [comment]
@Lintom Koin is using an older stately version, so you need to add `stately-common` explicitly.

See details: https://github.com/cashapp/sqldelight/issues/4357#issuecomment-1839905700

**Comment by Lintom** [comment]
> @Lintom Koin is using an older stately version, so you need to add `stately-common` explicitly.
> 
> See details: [cashapp/sqldelight#4357 (comment)](https://github.com/cashapp/sqldelight/issues/4357#issuecomment-1839905700)

@kpgalligan Problem is solved. Thank you very much.
