### ISSUE TITLE
Linked List implementation

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/Stately#25]
This is for v1 and isolated state. Need an implementation of linked list that is just standard mutable state. Does not need to be concurrent. Will wrap with isolated state.

Needs solid testing, of course. Alternatively, a link to good, properly licensed, community implementations.

**Comment by JakeWharton** [comment]
ArrayDeque is in 1.3.70 stdlib. Do you need something more than that?

**Comment by kpgalligan** [comment]
That's interesting. I have to have some more discussion, thought around what's actually "needed". Had an lrucache in the original stately collections that was using a linked list to manage the "ru" ordering. Was looking to replace what was in there, but I think there's a general desire for some more collection types that don't necessarily need to live in the stdlib. Wrapping and isolating them to a thread to make them concurrent is relatively easy.

ArrayDeque is pretty interesting, though. Just in general.
