### ISSUE TITLE
kotlin 1.3.70 - Version v1.0.0-a2 not published

### ISSUE THREAD

**Issue by tspoke** [touchlab/Stately#30]
Hello,

I'm trying to add the latest version of Stately to my project (setup with kotlin 1.3.70) and I'm not able to find anywhere the latest version on maven.
I can see the version v1.0.0-a2 released on github but it's not published yet ?

Thanks !

**Comment by kpgalligan** [comment]
The modules have changed. There's no "stately". There's "stately-common", "stately-concurrency", etc.
