### ISSUE TITLE
Creating IsolateState off the main thread on iOS throws an exception

### ISSUE THREAD

**Issue by galsh83** [touchlab/Stately#31]
IsolateState cannot be created on non-main threads on iOS. The following exception is thrown: `Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread`

Creating the deprecated collections (from stately-collections) did work off the main thread. For example:

```
val worker = Worker.start()
worker.execute(TransferMode.SAFE, {}) {
    try {
        val bar = frozenLinkedList<String>()
        val foo = IsolateState { mutableListOf<String>() }
    } catch(e: Throwable) {
        print("Error: $e")
    }
}
```

The above code throws on `val foo = IsolateState { mutableListOf<String>() }`, but not on `val bar = frozenLinkedList<String>()`

**Comment by kpgalligan** [comment]
Good catch. Absolutely would be an issue. Our testing was calling from main thread.

**Comment by kpgalligan** [comment]
Fixed in https://github.com/touchlab/Stately/releases/tag/v1.0.0-a3
