### ISSUE TITLE
dispose() is not closing internal ThreadExecutor

### ISSUE THREAD

**Issue by YarStroTR** [touchlab/Stately#34]
When using collections on JVM,  StateHolder leverages defaultStateRunner (BackgroundStateRunner for JVM) which in turn creates Executors.newSingleThreadExecutor().
As a result java application cannot finish ( non-daemon thread is running ).
To resolve this dispose would need to close that Executor, and let application that uses this library to exit.

**Comment by CommanderTvis** [comment]
It is a major issue, which has no workarounds from user code except adding `exitProcess(0)` call.

**Comment by CommanderTvis** [comment]
It's quite a major issue because `shutdownIsoRunner` is not always convenient to call.

**Comment by ArcticLampyrid** [comment]
how about setting daemon flag for the background thread?

**Comment by kpgalligan** [comment]
This was fixed a while ago but not closed...
