### ISSUE TITLE
Support for KN 1.3.72

### ISSUE THREAD

**Issue by necrogt4** [touchlab/Stately#39]
When running a KN v1.3.71 iOS project I run into the error "The abi versions don't match. Expected '[22]', found '17'." for the Stately v0.10.2 libraries."

It appears they we're compiled with KN 1.3.61 and I am unable to downgrade due to other library compatibility issues.

Are there plans to update to the latest 1.3.72 KN libraries for compilation? There does not appear to be any issue when compiling Stately using KN 1.3.72, well not with the limited usage I have with Stately in my project anyway.

**Comment by kpgalligan** [comment]
Stately has moved to 1.0+. The package structure has changed a bit, but everything is there. For 1.3.7x, use Stately version 1.0.3.

What are you using from Stately?

**Comment by necrogt4** [comment]
I'm just using IsolateState to manage a shared map, nothing fancy.

Hmm, I'm not able to find "co.touchlab:stately:1.0.3" when using mavenCentral(). Should I be looking elsewhere? Also a quick search on https://search.maven.org/ is showing the last released version as 0.10.2.

Am I missing something?

**Comment by omainegra** [comment]
I believe that artifact is not the right one (or not anymore).  In the README they're enumerated. I'm using [stately-isolate](https://github.com/touchlab/Stately#stately-isolate), version [1.0.3-a4](https://mvnrepository.com/artifact/co.touchlab/stately-isolate-jvm/1.0.3-a4) and Kotlin **1.3.72**. The version with **-1.4-M2** suffix is for Kotlin **1.4-M2**
