### ISSUE TITLE
Support Kotlin 1.4

### ISSUE THREAD

**Issue by minaEweida** [touchlab/Stately#43]
Hi, is there a plan to support kotlin 1.4 soon?

**Comment by ge-org** [comment]
I believe [v1.1.0](https://github.com/touchlab/Stately/releases/tag/1.1.0) supports Kotlin 1.4

**Comment by vdesmet93** [comment]
Looks like 1.1.0 is not available on Maven Central yet 😕

**Comment by ge-org** [comment]
@vdesmet93 you can use 1.1.0-a1 for now

**Comment by martinbonnin** [comment]
I guess this can be closed with https://github.com/touchlab/Stately/releases/tag/1.1.0?

**Comment by minaEweida** [comment]
Thanks
