### ISSUE TITLE
HMPP (Hierarchical Projects) support? 

### ISSUE THREAD

**Issue by martinbonnin** [touchlab/Stately#46]
Follow up from https://github.com/cashapp/sqldelight/issues/1992

Are there any plans to enable [HMPP](https://kotlinlang.org/docs/reference/mpp-share-on-platforms.html#share-code-on-similar-platforms)? From my current understanding, this would be required if any downstream app/lib enables HMPP.

**Comment by LouisCAD** [comment]
@kpgalligan Should we send a PR?

**Comment by kpgalligan** [comment]
I tried adding HMPP to Stately and TestHelp dependency, but there are still build and IDE issues. See issue in TestHelp and linked Kotlin slack chat. We're *almost* ready. Should be able to enable in `gradle.properties` when ready.

https://github.com/touchlab/Stately/blob/main/gradle.properties#L42

Will leave this open and revisit when HMPP issues are resolved.

**Comment by LouisCAD** [comment]
For reference, here's the issue blocking that one: https://youtrack.jetbrains.com/issue/KT-45163

**Comment by CommanderTvis** [comment]
This issue should be closed since the latest Stately version can be successfully used from HMPP projects.

**Comment by twyatt** [comment]
> This issue should be closed since the latest Stately version can be successfully used from HMPP projects.

@CommanderTvis it does not appear that Stately has enabled HMPP support yet (i.e. `enableGranularSourceSetsMetadata` has not been enabled in [`gradle.properties`](https://github.com/touchlab/Stately/blob/711d7213a49c0da275703023c294303a374ac96d/gradle.properties#L42)).

Perhaps you know of a workaround?

**Comment by kpgalligan** [comment]
> This issue should be closed since the latest Stately version can be successfully used from HMPP projects.

We'll close it when we add support, but we're waiting on tooling. As for workarounds, @twyatt , you can try adding this to your `gradle.properties`

```
kotlin.mpp.enableCompatibilityMetadataVariant=true
```

**Comment by twyatt** [comment]
@kpgalligan I do have that option enabled, but I'm hitting compilation failures when I go HMPP (https://github.com/JuulLabs/kable/pull/63).

Currently utilizing symlinks to hobble things together in a pre-HMPP world, but it is working, so, no rush. Appreciate your libraries and will be excited when upstream removes your blockers.

**Comment by kpgalligan** [comment]
We saw some demos of progress on HMPP in future releases (in the IDE and tooling). It's complicated stuff, and I have no idea on timelines, but fixes do appear to be coming. Hopefully things improve in 1.5.20 and beyond.

**Comment by kpgalligan** [comment]
Fixed in Kotlin 1.5.30. Stately release 1.1.9-hmpp with Kotlin 1.5.30-RC. Thanks @sellmair!
