### ISSUE TITLE
Missing 1.1.0 release for Stately iso-collections and isolate

### ISSUE THREAD

**Issue by MateuszKrawczuk** [touchlab/Stately#48]
Hi, I tried to build a project with isolate, but I noticed there is only a 1.1.0 release for concurrency and common, but it is missing for isolate and iso collections. The last release for them was 1.1.0-a1. Could you explain why it is missing?

**Comment by kpgalligan** [comment]
Not sure why that's missing. Updated releases: https://github.com/touchlab/Stately/releases/tag/1.1.3

**Comment by kpgalligan** [comment]
See maven search for exact deployment and config: https://search.maven.org/search?q=stately-isolate
