### ISSUE TITLE
Missing api dependency

### ISSUE THREAD

**Issue by PaulWoitaschek** [touchlab/Stately#49]
Currently I get compilation errors when adding the `stately-iso-collections` dependency and using an `IsoMutableMap`.

The `compileKotlinJvm` task fails with:
```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class co.touchlab.stately.collections.IsoMutableMap, unresolved supertypes: co.touchlab.stately.isolate.IsolateState
```

Apparently this is due to the dependency not being propagated properly.
This line should have an `api` not an `implementation` dependency:

https://github.com/touchlab/Stately/blob/d0225a201d6adeb0e1911df1459bd60746d187bb/stately-iso-collections/build.gradle#L61

(tested using co.touchlab:stately-iso-collections:1.1.1-a1)

**Comment by kpgalligan** [comment]
Added for that particular module. Will take a look at others to see if they also make sense, but for now see v1.1.4.

**Comment by william-reed** [comment]
@kpgalligan I'm unable to upgrade to 1.1.4 since its compiled with kotlin 1.4.30 and not all of my dependencies have been updated yet (SqlDelight). Is there anyway I can avoid this problem without upgrading to stately 1.1.4?

I've tried by adding stately-concurrency with the same issue:
```
implementation("co.touchlab:stately-concurrency:1.1.0")
implementation("co.touchlab:stately-iso-collections:1.1.0-a1")
```
