### ISSUE TITLE
AtomicReference memory issues

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/Stately#5]
Apparently AtomicReference in native does not reclaim memory when being collected. This detail wasn't obvious early on, and the docs imply it "might" leak, but I'm pretty sure it'll always leak (or always won't)

https://github.com/JetBrains/kotlin-native/blob/master/runtime/src/main/kotlin/kotlin/native/concurrent/Atomics.kt#L207

Should petition K/N team for something more robust, but for now, we'll deal. Possibly register atomics to deallocate with weak references, although it'll probably be easier to simply make sure we clean up unnecessary data.

**Comment by avently** [comment]
@kpgalligan the stored objects are BigDecimals only, 48 bytes per object. From 50.000 to 1.000.000 objects in total per app, without cache this numbers would be multiplied by 2.
