### ISSUE TITLE
Kotlin 1.5-compatible release

### ISSUE THREAD

**Issue by JakeWharton** [touchlab/Stately#58]
Tracking issue as Kotlin 1.5 appears to be starting to roll out

**Comment by kpgalligan** [comment]
https://github.com/touchlab/SQLiter/releases/tag/1.0.3

**Comment by twyatt** [comment]
> https://github.com/touchlab/SQLiter/releases/tag/1.0.3

Was this message intended for https://github.com/touchlab/SQLiter/issues/43?

**Comment by kpgalligan** [comment]
Yeah, juggling multiple windows. https://github.com/touchlab/Stately/releases/tag/1.1.7
