### ISSUE TITLE
What's the advantage for GuardedStableRef instead of WorkerBoundReference?

### ISSUE THREAD

**Issue by ArcticLampyrid** [touchlab/Stately#60]
No offense, I'm just curious.

**Comment by kpgalligan** [comment]
Closing old issues. On the question of WorkerBoundReference, I honestly haven't used that. StableRef was around much longer. Maybe WorkerBoundReference would be a good replacement? Stately's focus is shifting with the new memory model, though, so not sure we'll do more than maintenance work on certain concurrency modules.
