### ISSUE TITLE
IsolateStateProperty

### ISSUE THREAD

**Issue by PaulWoitaschek** [touchlab/Stately#61]
In our tests we have a class that will be frozen with a mutable var that holds an enum property.

```kotlin
internal class MockDietApi : DietApi {

  private var diet: Diet = Diet.NoPreference

  override suspend fun get(): Diet {
    return diet
  }

  override suspend fun update(diet: Diet) {
    this.diet = diet
  }
}
```

Now I can't use that class because updating the diet would cause an invalid mutability exception.
In this case I can't wrap it in an `IsolateState` because the enum itself is deeply immutable. As a workaround I can create a box class with a var that holds that value.

As I had this in multiple places, I've created a delegate for this.

```kotlin
private class IsolateStateProperty<T>(initial: T) : ReadWriteProperty<Any, T> {

  private class Box<T>(var value: T)

  private val state = IsolateState {
    Box(initial)
  }

  override fun setValue(thisRef: Any, property: KProperty<*>, value: T) {
    state.access { it.value = value }
  }

  override fun getValue(thisRef: Any, property: KProperty<*>): T {
    return state.access { it.value }
  }
}

fun <T> isolateState(initial: T): ReadWriteProperty<Any, T> = IsolateStateProperty(initial)
```

Now with that property in place the mock class can be simply written using that property delegate and the usage feels very intuitive.

```kotlin
internal class MockDietApi : DietApi {

  private var diet: Diet by isolateState(Diet.NoPreference)

  override suspend fun get(): Diet {
    return diet
  }

  override suspend fun update(diet: Diet) {
    this.diet = diet
  }
}
```

Is there a better solution? If not, I'd happily open a PR.

**Comment by kpgalligan** [comment]
Going through old issues. We haven't done a lot for iSO since the announcement around the new memory model. Closing for now, although I do kind of like this.
