### ISSUE TITLE
Call to check new memory model

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/Stately#68]
Some code that will hopefully check if we're in the new memory model: https://github.com/touchlab/Stately/tree/kpg/new_memory_model

Add config to get this to run on the new memory model and confirm this works: https://github.com/JetBrains/kotlin/blob/master/kotlin-native/NEW_MM.md

We should also add a test but we'll need to pass in some flag to tell the test what to expect.

**Comment by findjigar** [comment]
Closing an old and stale issue
