### ISSUE TITLE
Align auto-freeze

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/Stately#7]
AtomicReference from kotlin native does not automatically freeze data. Stately collections do. Stately's AtomicReference should probably act the same as the collections. Either auto-freeze, of review if maybe collections shouldn't auto-freeze.

Some other options might be to add some lint checks, or let the user config if the structures auto-freeze.

**Comment by Dkhusainov** [comment]
I think it should autofreeze, less work on the consumer side.

**Comment by kpgalligan** [comment]
Wound up autofreezing
