### ISSUE TITLE
Kotlin 1.6-compatible release

### ISSUE THREAD

**Issue by JakeWharton** [touchlab/Stately#73]
Just a tracking issue

**Comment by russhwolf** [comment]
Assuming [experimental compatibility](https://youtrack.jetbrains.com/issue/KT-42293) holds up, it should be possible to use the current version with Kotlin 1.6.

**Comment by JakeWharton** [comment]
Ah, nice. I knew 1.4/1.5 did it but I assumed 1.6 would break it since they originally said every other. I'll be perfectly happy for this issue to be closed with no changes needed!

**Comment by kpgalligan** [comment]
[1.2.2 ](https://github.com/touchlab/Stately/releases/tag/1.2.2) targets 1.6.20
