### ISSUE TITLE
Add api checking to non-deprecated modules

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/Stately#84]
Use the binary-compatability-validator plugin. Example in [kermit](https://github.com/touchlab/Kermit/blob/b5e86bd2700b354b6db5ff12a0fd51c5b3b991be/build.gradle.kts#L29)

Kermit also shows configuration for ignoring modules

**Comment by samhill303** [comment]
Should be based on the new memory model branch. It should be clear which modules are deprecated there
