### ISSUE TITLE
Kotlin JS - production can't resolve 's-stately-common'

### ISSUE THREAD

**Issue by Coneys** [touchlab/Stately#86]
Hello!

I am trying to use stately in multiplatform project, but after trying to build javascript artifact for browser error occurs:
`Module not found: Error: Can't resolve 's-stately-common'`

By looking on files, error message is right, s-stately-common doesn't exists in ../build/js/packages/xxx/kotlin-dce:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/20384394/190388043-f91ddfa0-65eb-4a6d-9ab4-b080c75f339c.png">

In my gradle I only added those lines:
```
 api("co.touchlab:stately-isolate:1.2.3")
 api("co.touchlab:stately-common:1.2.3")
```

Project is currently on Kotlin 1.6.10, with new memory management enabled

**Comment by russhwolf** [comment]
I believe Stately 1.2.3 was build with Kotlin 1.6.20, so maybe try bumping Kotlin and see if that helps. Also if you're still using the legacy js backend, consider moving to IR instead.

**Comment by Coneys** [comment]
Okey, so Kotlin version wasn't issue, I had to switch to IR backend, now it works

**Comment by Coneys** [comment]
Is t here any reason why library wasn't published for Legacy and IR backend? On production we use IR, but for development purposes we still are using Legacy version and now its broken

**Comment by russhwolf** [comment]
Good to know. We're publishing both so I'm not sure why it wouldn't work, but also I don't think there's any effort still going into the legacy backend these days so it's easy to believe something might have gotten broken by mistake.
