### ISSUE TITLE
Is it still required to freeze and ensureNeverFrozen with Kotlin 1.7.20?

### ISSUE THREAD

**Issue by mlostekk** [touchlab/Stately#88]
I have just read that 1.7.20 implements the new memory manager. (https://kotlinlang.org/docs/native-memory-manager.html) And here it's stated that several things are not required anymore. Such as `ensureNeverFrozen` and `freeze`.

Is it safe in an Android/iOS shared project to remove my constructor that calls `ensureNeverFrozen`

```kotlin
class L10NService(private val deviceLocale: String) : L10n {

    /// Constructor
    init {
        // ensureNeverFrozen() -> not required anymore
    }
}
```

as well as my `IODispatcher` in `iosMain`

```kotlin

/// The actual dispatcher on iOS
@Suppress("unused")
actual val mainDispatcher: CoroutineContext
    get() = IODispatcher

// Mapper of swift style dispatch to kotlin style dispatching
private object IODispatcher : CoroutineDispatcher() {
    override fun dispatch(context: CoroutineContext, block: Runnable) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT.toLong(), 0.toULong())) {
            try {
                block.run() //.freeze() -> not requred anymore
            } catch (err: Throwable) {
                throw err
            }
        }
    }
}

```

Is that correct?

**Comment by kpgalligan** [comment]
Yes. You can remove the freeze-related code. Many libraries still assume the freeze semantics, but I haven't run into major issues so far. Stately is getting an update at some point, essentially deprecating the features from the old memory model, but adding some simpler concurrent collections.
