### ISSUE TITLE
Native target - linuxArm64

### ISSUE THREAD

**Issue by arnaudgiuliani** [touchlab/Stately#98]
Hello,

Koin framework is using stately and the `linuxArm64` native target has been asked. I can check to make a PR perhaps.

Thanks.

**Comment by kpgalligan** [comment]
Hey! I'll get this into the pipeline. It's a tight week with Droidcon coming up, so send a PR if you're in a rush, but otherwise we'll get somebody on it soon.

**Comment by arnaudgiuliani** [comment]
sure, if I have time I send you something 👍

**Comment by kpgalligan** [comment]
https://github.com/touchlab/Stately/releases/tag/2.0.0

**Comment by arnaudgiuliani** [comment]
Thanks @kpgalligan 👌

**Comment by kpgalligan** [comment]
@arnaudgiuliani Very important!!! don't use that release. The KMP publishing and Gradle had some change in newer versions that pushed artifacts, but the dates, etc, are all off. I updated the whole deploy process. Use 2.0.2

https://github.com/touchlab/Stately/releases/tag/2.0.2

**Comment by arnaudgiuliani** [comment]
thanks @kpgalligan 👍
